# -*- coding: utf-8 -*-
"""weather_stationsFinal.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1xVSuoIPdTQEnl-9jGYJvgDykrqLi2XL4

#Install and Import
"""

!pip install matplotlib import basemap
!pip install basemap matplotlib

from mpl_toolkits.basemap import Basemap
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

pip install learn2map

from geopy.geocoders import ArcGIS

nom = ArcGIS()

nom.geocode('chitwan')

"""#Check geo location

"""

s = nom.geocode('kathmandu')

s.latitude

s.longitude

"""#Install folium and import"""

pip install folium

import folium

map =folium.Map(location= [27.58493923900005,84.43457351300003],zoom_start = 10)

map

#add child method
map.add_child(folium.Marker(location=[27.58493923900005,84.43457351300003],popup='chitwan',icon = folium.Icon(color='blue')))

"""#color from blue to red on same code  

"""

fg=folium.FeatureGroup(name="data")
fg.add_child(folium.Marker(location=[27.58493923900005,84.43457351300003],popup='chitwan',icon = folium.Icon(color='red')))
map.add_child(fg)

"""#Install and import pandas"""

pip install pandas

import pandas as pd

import warnings
warnings.filterwarnings("ignore")

"""#Link Google Drive"""

from google.colab import drive
drive.mount('/content/drive')

"""#Import CSV file"""

data = pd.read_csv('/content/drive/MyDrive/project work data/data cal/colab/Data/ground_data /groundstations.csv')

data.head(5) #check proper number of title Index by head method

data #again check of csv file all details completely.

a_list= data[['Station Index','District',"Latitude",'Longitude']].values.tolist() # assign above Index with proper arrangement

a_list

import folium
data_map=folium.Map(location =[26.68666667,87.87888889])
fg=folium.FeatureGroup(name="data")



for i in a_list:

  fg.add_child(folium.Marker(location=[i[2],i[3]],popup=i[1],icon=folium.Icon(color="pink")))
data_map.add_child(fg)

data_map.save("bagmati.html")#you can save your data in any format like jpg,png and html